#!/bin/bash -e

sudo apt-get update

sudo apt-get install nginx

sudo ufw allow 'Nginx HTTP'

sudo systemctl status nginx # look for active (running)

sudo systemctl enable nginx

sudo mkdir -p /var/www/psetse.com/html

sudo chown -R $USER:$USER /var/www/psetse.com/html

sudo chmod -R 0755 /var/www

# git clone pse/tse index.html file

sudo cp /tmp/...../index.html /var/www/psetse.com/html

sudo cp # from cloned puppet directory /etc/nginx/sites-available/psetse.com

sudo ln -s /etc/nginx/sites-available/psetse.com /etc/nginx/sites-enabled

sudo nginx -t

sudo systemctl restart nginx

## Log status of the Puppet run
if [ $? -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi
